# docker-compose.yml
version: '3'
services:
  postgres:
      image: postgres # use latest official postgres version
      environment:
        POSTGRES_PASSWORD: uhncrtdesw89o8gtfg53e46juy8i9ortl8
        POSTGRES_USER: admin
        POSTGRES_DB: wattohm
      volumes:
        - postgres-data:/var/lib/postgresql/data
      ports:
        - '5432:5432'
  wattohm:
    image: sarontetra/wattohm
    ports:
      - '8080:8080'
volumes:
  postgres-data: