[default]
address = "0.0.0.0"
port = 8080

[default.databases]
postgres = { url = "postgres://admin:uhncrtdesw89o8gtfg53e46juy8i9ortl8@localhost:5432/wattohm" }

[release.databases]
postgres = { url = "postgres://admin:uhncrtdesw89o8gtfg53e46juy8i9ortl8@postgres:5432/wattohm" }
