# docker-compose.yml
version: '3'
services:
  postgres:
      image: postgres # use latest official postgres version
      environment:
        POSTGRES_PASSWORD: uhncrtdesw89o8gtfg53e46juy8i9ortl8
        POSTGRES_USER: admin
        POSTGRES_DB: wattohm
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      ports:
        - '5432:5432'